### ISSUE TITLE
About the 4 missing buttons

### ISSUE THREAD

**Issue by Cosetto** [yountl/biniku#1]
This dll should be able to patch them
![image](https://github.com/yountl/biniku/assets/81801486/ce612e82-e1c5-4771-8047-23d7f47cb00e)
[d3d9.zip](https://github.com/yountl/biniku/files/15445860/d3d9.zip)

**Comment by yountl** [comment]
Thanks a lot for the help @Cosetto ! I've published a new release with this DLL!

**Comment by Leticiel** [comment]
[mes.zip](https://github.com/yountl/biniku/files/15483856/mes.zip)

![image](https://github.com/yountl/biniku/assets/155957757/627e6337-914f-4551-a182-cd8f64fad142)

I fixed the text wrapping issues in the backlog.
